/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Idioma;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author Julio
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        idioma = new Idioma("2");
        //650,500
        initComponents();
        itemSaveGame.setVisible(false);
        setSize(1320, 890);//885
        setTitle(idioma.getProperty("titulo"));
        
        personalizar(jMenuItem1);
        personalizar(itemContinue);
        personalizar(itemJuegoNuevo);
        personalizar(itemSaveGame);
        personalizar(itemReports);
        personalizar(itemStatistics);
    }
  private void personalizar(JMenuItem item){
       Border line = new LineBorder(Color.DARK_GRAY);
        Border margin = new EmptyBorder(5, 10, 5, 10);
        Border compound = new CompoundBorder(line, margin);
        item.setBorder(compound);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panelPrincipal = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        menuJuego = new javax.swing.JMenu();
        itemJuegoNuevo = new javax.swing.JMenuItem();
        itemContinue = new javax.swing.JMenuItem();
        itemSaveGame = new javax.swing.JMenuItem();
        itemReports = new javax.swing.JMenuItem();
        itemStatistics = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        panelPrincipal.setLayout(null);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        panelPrincipal.add(lblFondo);
        lblFondo.setBounds(0, 0, 1320, 890);

        file.setText(idioma.getProperty("archivo"));

        menuJuego.setText(idioma.getProperty("juego"));

        itemJuegoNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mas.png"))); // NOI18N
        itemJuegoNuevo.setText(idioma.getProperty("juegoNuevo"));
        itemJuegoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemJuegoNuevoActionPerformed(evt);
            }
        });
        menuJuego.add(itemJuegoNuevo);

        itemContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        itemContinue.setText(idioma.getProperty("continuarJuego"));
        menuJuego.add(itemContinue);

        itemSaveGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.jpg"))); // NOI18N
        itemSaveGame.setText(idioma.getProperty("guardarJuego"));
        menuJuego.add(itemSaveGame);

        file.add(menuJuego);

        itemReports.setText(idioma.getProperty("reportes"));
        itemReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReportsActionPerformed(evt);
            }
        });
        file.add(itemReports);

        itemStatistics.setText(idioma.getProperty("estadistica"));
        itemStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStatisticsActionPerformed(evt);
            }
        });
        file.add(itemStatistics);

        barraMenu.add(file);

        edit.setText(idioma.getProperty("ayuda"));
        barraMenu.add(edit);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemJuegoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemJuegoNuevoActionPerformed
       
        for (Component component : panelPrincipal.getComponents()) {
            System.out.println(component.getClass().getCanonicalName());
            if (component.getClass().getCanonicalName().equalsIgnoreCase("Vistas.Juego")) {
                System.out.println("hay un juego en curso");
                JOptionPane.showMessageDialog(null, "Hay Un Juego En Curso", "Informacion", JOptionPane.WARNING_MESSAGE);
            }else{
                JPanel nuevo = new Juego();
                 addPanel(nuevo);
            }
        }
    }//GEN-LAST:event_itemJuegoNuevoActionPerformed

    private void itemReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReportsActionPerformed
        // TODO add your handling code here:
        JPanel deReporte = new Reportes();
        addPanel(deReporte);
        
    }//GEN-LAST:event_itemReportsActionPerformed

    private void itemStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemStatisticsActionPerformed
        // TODO add your handling code here:
        JPanel deEstadistica = new Estadistica();
        addPanel(deEstadistica);
    }//GEN-LAST:event_itemStatisticsActionPerformed
public void addPanel(JPanel panel){
    
        panel.setSize(1320, 890);
        panel.setLocation(0,0);
        panelPrincipal.removeAll();
        panelPrincipal.add(panel, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
}
public static void setVisibleSave(boolean visible){
    itemSaveGame.setVisible(visible);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Darcula".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    
    public static Idioma idioma;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu edit;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem itemContinue;
    private javax.swing.JMenuItem itemJuegoNuevo;
    private javax.swing.JMenuItem itemReports;
    private static javax.swing.JMenuItem itemSaveGame;
    private javax.swing.JMenuItem itemStatistics;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JMenu menuJuego;
    public static javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
