/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Reportes.Report;
import static Vistas.Principal.idioma;

/**
 *
 * @author Julio
 */
public class Reportes extends javax.swing.JPanel {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionTablero = new javax.swing.JDialog();
        mensaje = new javax.swing.JLabel();
        lblLstVehiculo = new javax.swing.JLabel();
        lblRBatalla = new javax.swing.JLabel();
        lblmVehiculo = new javax.swing.JLabel();
        lblPrVehiculo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        opcionTablero.setSize(350, 345);
        opcionTablero.setTitle(idioma.getProperty("dialogo"));
        opcionTablero.setAlwaysOnTop(true);
        opcionTablero.setLocation(new java.awt.Point(0, 0));
        opcionTablero.setType(java.awt.Window.Type.POPUP);
        opcionTablero.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensaje.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        mensaje.setForeground(new java.awt.Color(51, 51, 51));
        mensaje.setText(idioma.getProperty("tpReporte"));
        opcionTablero.getContentPane().add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 320, -1));

        lblLstVehiculo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblLstVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        lblLstVehiculo.setText(idioma.getProperty("lst-Vehiculos"));
        opcionTablero.getContentPane().add(lblLstVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 170, -1));

        lblRBatalla.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblRBatalla.setForeground(new java.awt.Color(0, 0, 0));
        lblRBatalla.setText(idioma.getProperty("rpt-batallas"));
        opcionTablero.getContentPane().add(lblRBatalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, -1));

        lblmVehiculo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblmVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        lblmVehiculo.setText(idioma.getProperty("mjr-Vehiculo"));
        opcionTablero.getContentPane().add(lblmVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 150, -1));

        lblPrVehiculo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblPrVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        lblPrVehiculo.setText(idioma.getProperty("pr-Vehiculo"));
        opcionTablero.getContentPane().add(lblPrVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dialogo.jpg"))); // NOI18N
        opcionTablero.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 335, 300));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Listado De Jugadores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 360, 60));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporteFondo.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Report nuevo = new Report();
        nuevo.writeReport();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLstVehiculo;
    private javax.swing.JLabel lblPrVehiculo;
    private javax.swing.JLabel lblRBatalla;
    private javax.swing.JLabel lblmVehiculo;
    private javax.swing.JLabel mensaje;
    private javax.swing.JDialog opcionTablero;
    // End of variables declaration//GEN-END:variables
}
