/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Archivos.RecuperarPlantilla;
import Clases.Jugador;
import static Vistas.Principal.idioma;
import static Vistas.Principal.panelPrincipal;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Julio
 */
public class SeleccinarJugador extends javax.swing.JPanel {

    /**
     * Creates new form SeleccinarJugador
     */
    public SeleccinarJugador() {
        initComponents();
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, Principal.idioma.getProperty("selectP"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        listPlayer2.setVisible(false);
        addElementList1();
        eventItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPlayer1 = new javax.swing.JList<>();
        btnPlayer1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPlayer2 = new javax.swing.JList<>();
        pc = new javax.swing.JButton();
        btnPlayer2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccionar Jugador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, idioma.getProperty("p1"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12)));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        listPlayer1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        listPlayer1.setMaximumSize(new java.awt.Dimension(205, 231));
        listPlayer1.setPreferredSize(new java.awt.Dimension(205, 231));
        listPlayer1.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(listPlayer1);

        btnPlayer1.setText(idioma.getProperty("sl"));
        btnPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnPlayer1)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlayer1)
                .addGap(21, 21, 21))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, idioma.getProperty("p2"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12), new java.awt.Color(102, 102, 102)));

        listPlayer2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        listPlayer2.setMaximumSize(new java.awt.Dimension(205, 231));
        listPlayer2.setPreferredSize(new java.awt.Dimension(205, 231));
        jScrollPane2.setViewportView(listPlayer2);

        pc.setText(idioma.getProperty("pC"));
        pc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcActionPerformed(evt);
            }
        });

        btnPlayer2.setText(idioma.getProperty("sl"));
        btnPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(pc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlayer2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pc)
                    .addComponent(btnPlayer2))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer1ActionPerformed
        ;
        searchPlayer(listPlayer1.getSelectedIndex());
    }//GEN-LAST:event_btnPlayer1ActionPerformed
    public void searchPlayer(int index){
        if (listPlayer1.getSelectedIndex()!= -1) {
            
          //  listPlayer1.getSelectedIndex();
            RecuperarPlantilla<Jugador> recuperar = new RecuperarPlantilla<>();
            File player = new File(Principal.mkdirPlayer+index+".player");
            Principal.uno = recuperar.recuperar(Principal.mkdirPlayer+listPlayer1.getSelectedIndex()+".player");
            listPlayer2.setVisible(true);
            listPlayer1.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe Seleccionar Un Jugador", "Informacion", JOptionPane.WARNING_MESSAGE);
        }
    }
    public void eventItem(){
        listPlayer1.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e){
                 JList list = (JList)e.getSource(); 
                 if (e.getClickCount() == 2) {
                     int index = list.locationToIndex(e.getPoint()); 
                     searchPlayer(index);
                 }
            }
         });
        listPlayer2.addMouseListener(new MouseAdapter() {
                
            public void mouseClicked(MouseEvent e){
                 JList list = (JList)e.getSource(); 
                 if (e.getClickCount() == 2) {
                     int index = list.locationToIndex(e.getPoint()); 
                     searchPlayerDos(index);
                 }
            }
        });
    }
    private void btnPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer2ActionPerformed
        // TODO add your handling code here:
        int index = listPlayer2.getSelectedIndex();
        searchPlayerDos(index);
       
    }//GEN-LAST:event_btnPlayer2ActionPerformed
    public void searchPlayerDos(int index){
         if (listPlayer1.getSelectedIndex()!= index && index != -1 ) {
            
            
            RecuperarPlantilla<Jugador> recuperar = new RecuperarPlantilla<>();
            Principal.dos = recuperar.recuperar(Principal.mkdirPlayer+index+".player");
             
            initGame();
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe Seleccionar Un Jugador", "Informacion", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void pcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcActionPerformed
        Jugador nuevo = new Jugador("PC-");
        nuevo.setNombre(nuevo.getNombre()+nuevo.getMyId());
    }//GEN-LAST:event_pcActionPerformed
public void initGame(){
     int componen = panelPrincipal.getComponents().length;
        for (Component component : panelPrincipal.getComponents()) {
                    componen--;
                    System.out.println(component.getClass().getCanonicalName());
                    if (component.getClass().getCanonicalName().equalsIgnoreCase("Vistas.Juego")) {
                        System.out.println("hay un juego en curso");
                        JOptionPane.showMessageDialog(null, "Hay Un Juego En Curso", "Informacion", JOptionPane.WARNING_MESSAGE);
                        
                        //componen=-1;
                        break;
                    }else if (componen == 0){
                        JPanel nuevo = new Juego();
                         addPanel(nuevo);
                   //      nuevo.repaint();
                         //panelPrincipal.repaint();
                    }
        }
}
public void addPanel(JPanel panel){
    
        panel.setSize(panelPrincipal.getWidth() , 730 );
        panel.setLocation(0,0);
       
        panelPrincipal.removeAll();
        panelPrincipal.add(panel, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
}
    public void addElementList1(){
        
        RecuperarPlantilla<Jugador> recuperar = new RecuperarPlantilla<>();
        File jugador = new File("Player");
        String[] player = new String[jugador.list().length-1];
        int index =0;
        for (String string : jugador.list()) {
            if (string.contains(".")) {
                
                Jugador recuperado = recuperar.recuperar(Principal.mkdirPlayer, string, "");
             //   players.add();
                player[index] = String.valueOf(recuperado.getMyId())+". "+recuperado.getNombre();
                index++;
            }
        }
        listPlayer1.setListData(player);
        listPlayer2.setListData(player);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlayer1;
    private javax.swing.JButton btnPlayer2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listPlayer1;
    private javax.swing.JList<String> listPlayer2;
    private javax.swing.JButton pc;
    // End of variables declaration//GEN-END:variables
}
